/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.easyconference.presentation;

import com.easyconference.domain.entities.Article;
import com.easyconference.domain.entities.Usuario;
import com.easyconference.domain.service.ArticleService;
import com.easyconference.domain.service.Observer;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyVetoException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Ashlee Campaz
 */
public class GUIcontainer extends javax.swing.JFrame implements Observer{
    private Usuario usuario;
    private  ArticleService articleService;
    
    /**
     * Creates new form GUIcontainer
     */
    public GUIcontainer(Usuario us, ArticleService art) {
        this.usuario = us;
        this.articleService = art;
        initComponents();
        
    }
    
    public GUIcontainer(){}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlFondo = new javax.swing.JPanel();
        dskpaneContenedor = new javax.swing.JDesktopPane();
        intfInicio = new javax.swing.JInternalFrame();
        lbBienvenido = new javax.swing.JLabel();
        pnlListadoAr = new javax.swing.JPanel();
        lbListadoAr = new javax.swing.JLabel();
        scrlpArticulos = new javax.swing.JScrollPane();
        lstArticulos = new javax.swing.JList<>();
        pnlBotonSubirArt = new javax.swing.JPanel();
        lbSubirArticulo = new javax.swing.JLabel();
        pnlSuperior = new javax.swing.JPanel();
        lbeasyConference = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(873, 650));
        setSize(new java.awt.Dimension(873, 650));

        pnlFondo.setMinimumSize(new java.awt.Dimension(873, 650));
        pnlFondo.setPreferredSize(new java.awt.Dimension(873, 650));
        pnlFondo.setLayout(new java.awt.BorderLayout());

        dskpaneContenedor.setSelectedFrame(intfInicio);
        dskpaneContenedor.setLayout(new java.awt.BorderLayout());

        intfInicio.setBackground(new java.awt.Color(255, 255, 255));
        intfInicio.setBorder(null);
        intfInicio.setFrameIcon(null);
        intfInicio.setMinimumSize(new java.awt.Dimension(873, 650));
        intfInicio.setPreferredSize(new java.awt.Dimension(873, 650));
        intfInicio.setVisible(true);
        try {
            intfInicio.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GUIcontainer.class.getName()).log(Level.SEVERE, null, ex);
        }
        intfInicio.getContentPane().setLayout(new java.awt.GridBagLayout());

        lbBienvenido.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        lbBienvenido.setText("Bienvenido! "+ usuario.getName() + " " + usuario.getLastName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 479;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(95, 56, 0, 0);
        intfInicio.getContentPane().add(lbBienvenido, gridBagConstraints);

        pnlListadoAr.setBackground(new java.awt.Color(236, 236, 236));
        pnlListadoAr.setPreferredSize(new java.awt.Dimension(136, 204));
        pnlListadoAr.setLayout(new java.awt.BorderLayout());

        lbListadoAr.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbListadoAr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbListadoAr.setText("Listado de articulos");
        lbListadoAr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197)));
        pnlListadoAr.add(lbListadoAr, java.awt.BorderLayout.PAGE_START);

        scrlpArticulos.setViewportView(lstArticulos);

        pnlListadoAr.add(scrlpArticulos, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.ipady = 204;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 22, 98, 0);
        intfInicio.getContentPane().add(pnlListadoAr, gridBagConstraints);

        pnlBotonSubirArt.setBackground(new java.awt.Color(129, 218, 199));
        pnlBotonSubirArt.setLayout(new java.awt.BorderLayout());

        lbSubirArticulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbSubirArticulo.setForeground(new java.awt.Color(255, 255, 255));
        lbSubirArticulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSubirArticulo.setText("Subir articulo");
        lbSubirArticulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbSubirArticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSubirArticuloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbSubirArticuloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbSubirArticuloMouseExited(evt);
            }
        });
        pnlBotonSubirArt.add(lbSubirArticulo, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 83;
        gridBagConstraints.ipady = 72;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 18, 0, 61);
        intfInicio.getContentPane().add(pnlBotonSubirArt, gridBagConstraints);

        dskpaneContenedor.add(intfInicio, java.awt.BorderLayout.CENTER);
        //getContentPane().add(intfInicio, java.awt.BorderLayout.CENTER);

        pnlFondo.add(dskpaneContenedor, java.awt.BorderLayout.CENTER);
        //getContentPane().add(dskpaneContenedor, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlFondo, java.awt.BorderLayout.CENTER);

        pnlSuperior.setBackground(new java.awt.Color(0, 153, 153));
        pnlSuperior.setPreferredSize(new java.awt.Dimension(1028, 52));
        pnlSuperior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 20));

        lbeasyConference.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbeasyConference.setForeground(new java.awt.Color(255, 255, 255));
        lbeasyConference.setText("easyConference");
        pnlSuperior.add(lbeasyConference);

        getContentPane().add(pnlSuperior, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(pnlSuperior, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbSubirArticuloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSubirArticuloMouseEntered
        // TODO add your handling code here:
        lbSubirArticulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15));
    }//GEN-LAST:event_lbSubirArticuloMouseEntered

    private void lbSubirArticuloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSubirArticuloMouseExited
        // TODO add your handling code here:
        lbSubirArticulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14));
    }//GEN-LAST:event_lbSubirArticuloMouseExited

    private void lbSubirArticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSubirArticuloMouseClicked
         GUIcontainer  contenedorArticulo = new GUIcontainer(usuario,articleService);
         contenedorArticulo.setDefaultCloseOperation(HIDE_ON_CLOSE);
         contenedorArticulo.addWindowListener(new WindowAdapter() {

             @Override
             public void windowClosing(WindowEvent e) {
               pnlBotonSubirArt.setVisible(true);
             }

         });
         articleService.addObserver(this);
        GUIcreateArticle crearArticulo = new GUIcreateArticle(usuario,articleService);
        try {

            crearArticulo.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GUIcontainer.class.getName()).log(Level.SEVERE, null, ex);
        }
        contenedorArticulo.dskpaneContenedor.add(crearArticulo, java.awt.BorderLayout.CENTER);

        pnlBotonSubirArt.setVisible(false);
        contenedorArticulo.intfInicio.setVisible(false);
        crearArticulo.setVisible(true);
        contenedorArticulo.setVisible(true);
        
        
    }//GEN-LAST:event_lbSubirArticuloMouseClicked

   
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskpaneContenedor;
    private javax.swing.JInternalFrame intfInicio;
    private javax.swing.JLabel lbBienvenido;
    private javax.swing.JLabel lbListadoAr;
    private javax.swing.JLabel lbSubirArticulo;
    private javax.swing.JLabel lbeasyConference;
    private javax.swing.JList<String> lstArticulos;
    private javax.swing.JPanel pnlBotonSubirArt;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlListadoAr;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JScrollPane scrlpArticulos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Object o) {

        List<Article> list = articleService.listarArticle();
       DefaultListModel model = new DefaultListModel();
        lstArticulos.setModel(model);
        model.addAll(list); 
    }
}
