/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.easyconference.presentation;

import com.easyconference.domain.entities.Usuario;
import com.easyconference.domain.service.ConferenceService;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Ashlee Campaz
 */
public class GUIcontainer extends javax.swing.JFrame {
    private Usuario usuario;
    private ConferenceService conferenceService; 
    /**
     * Creates new form GUIcontainer
     */
    public GUIcontainer(Usuario us, ConferenceService con) {
        this.usuario = us;
        this.conferenceService = con; 
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlFondo = new javax.swing.JPanel();
        dskpaneContenedor = new javax.swing.JDesktopPane();
        intfInicio = new javax.swing.JInternalFrame();
        lbBienvenido = new javax.swing.JLabel();
        txtfBusqueda = new javax.swing.JTextField();
        pnlListadoCon = new javax.swing.JPanel();
        lbListadoCon = new javax.swing.JLabel();
        pnlListadoAr = new javax.swing.JPanel();
        lbListadoAr = new javax.swing.JLabel();
        pnlBotonCrearCon = new javax.swing.JPanel();
        lbCrearCon = new javax.swing.JLabel();
        lbBtnBuscar = new javax.swing.JLabel();
        pnlSuperior = new javax.swing.JPanel();
        lbeasyConference = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(873, 650));
        setSize(new java.awt.Dimension(873, 650));

        pnlFondo.setMinimumSize(new java.awt.Dimension(873, 650));
        pnlFondo.setPreferredSize(new java.awt.Dimension(873, 650));
        pnlFondo.setLayout(new java.awt.BorderLayout());

        dskpaneContenedor.setSelectedFrame(intfInicio);
        dskpaneContenedor.setLayout(new java.awt.BorderLayout());

        intfInicio.setBackground(new java.awt.Color(255, 255, 255));
        intfInicio.setBorder(null);
        intfInicio.setFrameIcon(null);
        intfInicio.setMinimumSize(new java.awt.Dimension(873, 650));
        intfInicio.setPreferredSize(new java.awt.Dimension(873, 650));
        intfInicio.setVisible(true);
        try {
            intfInicio.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GUIcontainer.class.getName()).log(Level.SEVERE, null, ex);
        }
        intfInicio.getContentPane().setLayout(new java.awt.GridBagLayout());

        lbBienvenido.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        lbBienvenido.setText("Bienvenido! "+ usuario.getName() + " " + usuario.getLastName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 479;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(95, 56, 0, 0);
        intfInicio.getContentPane().add(lbBienvenido, gridBagConstraints);

        txtfBusqueda.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtfBusqueda.setText("Buscar conferencia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 373;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 267, 0, 0);
        intfInicio.getContentPane().add(txtfBusqueda, gridBagConstraints);

        pnlListadoCon.setBackground(new java.awt.Color(236, 236, 236));
        pnlListadoCon.setPreferredSize(new java.awt.Dimension(136, 204));
        pnlListadoCon.setLayout(new java.awt.BorderLayout());

        lbListadoCon.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbListadoCon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbListadoCon.setText("Listado de conferencias");
        lbListadoCon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197)));
        pnlListadoCon.add(lbListadoCon, java.awt.BorderLayout.PAGE_START);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.ipady = 204;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 46, 98, 0);
        intfInicio.getContentPane().add(pnlListadoCon, gridBagConstraints);

        pnlListadoAr.setBackground(new java.awt.Color(236, 236, 236));
        pnlListadoAr.setPreferredSize(new java.awt.Dimension(136, 204));
        pnlListadoAr.setLayout(new java.awt.BorderLayout());

        lbListadoAr.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbListadoAr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbListadoAr.setText("Listado de articulos");
        lbListadoAr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(197, 197, 197)));
        pnlListadoAr.add(lbListadoAr, java.awt.BorderLayout.PAGE_START);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.ipady = 204;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 22, 98, 0);
        intfInicio.getContentPane().add(pnlListadoAr, gridBagConstraints);

        pnlBotonCrearCon.setBackground(new java.awt.Color(129, 218, 199));
        pnlBotonCrearCon.setLayout(new java.awt.BorderLayout());

        lbCrearCon.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbCrearCon.setForeground(new java.awt.Color(255, 255, 255));
        lbCrearCon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCrearCon.setText("Crear conferencia");
        lbCrearCon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbCrearCon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCrearConMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCrearConMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCrearConMouseExited(evt);
            }
        });
        pnlBotonCrearCon.add(lbCrearCon, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 83;
        gridBagConstraints.ipady = 72;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 18, 0, 61);
        intfInicio.getContentPane().add(pnlBotonCrearCon, gridBagConstraints);

        lbBtnBuscar.setText("buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(57, 6, 0, 0);
        intfInicio.getContentPane().add(lbBtnBuscar, gridBagConstraints);

        dskpaneContenedor.add(intfInicio, java.awt.BorderLayout.CENTER);
        //getContentPane().add(intfInicio, java.awt.BorderLayout.CENTER);

        pnlFondo.add(dskpaneContenedor, java.awt.BorderLayout.CENTER);
        //getContentPane().add(dskpaneContenedor, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlFondo, java.awt.BorderLayout.CENTER);

        pnlSuperior.setBackground(new java.awt.Color(0, 153, 153));
        pnlSuperior.setPreferredSize(new java.awt.Dimension(1028, 52));
        pnlSuperior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 20));

        lbeasyConference.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbeasyConference.setForeground(new java.awt.Color(255, 255, 255));
        lbeasyConference.setText("easyConference");
        pnlSuperior.add(lbeasyConference);

        getContentPane().add(pnlSuperior, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(pnlSuperior, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbCrearConMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCrearConMouseEntered
        // TODO add your handling code here:
        lbCrearCon.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15));
    }//GEN-LAST:event_lbCrearConMouseEntered

    private void lbCrearConMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCrearConMouseExited
        // TODO add your handling code here:
        lbCrearCon.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14));
    }//GEN-LAST:event_lbCrearConMouseExited

    private void lbCrearConMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCrearConMouseClicked
        GUIcreateConference crearConferencia = new GUIcreateConference();
        GUIcreateArticle crearAriticulo = new GUIcreateArticle();
        try {
            //crearConferencia.setMaximum(true);
            crearAriticulo.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GUIcontainer.class.getName()).log(Level.SEVERE, null, ex);
        }
        dskpaneContenedor.add(crearAriticulo, java.awt.BorderLayout.CENTER);
        //dskpaneContenedor.add(crearConferencia, java.awt.BorderLayout.CENTER);
        intfInicio.setVisible(false);
        crearAriticulo.setVisible(true);
        //crearConferencia.setVisible(true);
        
    }//GEN-LAST:event_lbCrearConMouseClicked

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskpaneContenedor;
    private javax.swing.JInternalFrame intfInicio;
    private javax.swing.JLabel lbBienvenido;
    private javax.swing.JLabel lbBtnBuscar;
    private javax.swing.JLabel lbCrearCon;
    private javax.swing.JLabel lbListadoAr;
    private javax.swing.JLabel lbListadoCon;
    private javax.swing.JLabel lbeasyConference;
    private javax.swing.JPanel pnlBotonCrearCon;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlListadoAr;
    private javax.swing.JPanel pnlListadoCon;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JTextField txtfBusqueda;
    // End of variables declaration//GEN-END:variables
}
